<a href="https://colab.research.google.com/github/amitav710/Calorie-Estimation-YOLOv5/blob/main/CalorieEstimation.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#clone YOLOv5 and 
!git clone https://github.com/ultralytics/yolov5  # clone repo
%cd yolov5
%pip install -qr requirements.txt # install dependencies
%pip install -q roboflow

import torch
import os
from IPython.display import Image, clear_output  # to display images

print(f"Setup complete. Using torch {torch.__version__} ({torch.cuda.get_device_properties(0).name if torch.cuda.is_available() else 'CPU'})")

Cloning into 'yolov5'...
remote: Enumerating objects: 13025, done.
remote: Counting objects: 100% (200/200), done.
remote: Compressing objects: 100% (92/92), done.
remote: Total 13025 (delta 123), reused 177 (delta 108), pack-reused 12825
Receiving objects: 100% (13025/13025), 12.40 MiB | 14.21 MiB/s, done.
Resolving deltas: 100% (8951/8951), done.
/content/yolov5
     |████████████████████████████████| 596 kB 4.3 MB/s 
     |████████████████████████████████| 145 kB 4.2 MB/s 
     |████████████████████████████████| 178 kB 63.3 MB/s 
     |████████████████████████████████| 4.3 MB 64.4 MB/s 
     |████████████████████████████████| 1.1 MB 25.0 MB/s 
     |████████████████████████████████| 21.6 MB 1.9 MB/s 
     |████████████████████████████████| 67 kB 3.6 MB/s 
     |████████████████████████████████| 54 kB 2.6 MB/s 
     |████████████████████████████████| 138 kB 54.7 MB/s 
     |████████████████████████████████| 62 kB 419 kB/s 
ERROR: pip's dependency resolver does not currently take into

In [ ]:
from roboflow import Roboflow
rf = Roboflow(model_format="yolov5", notebook="ultralytics")

upload and label your dataset, and get an API KEY here: https://app.roboflow.com/?model=yolov5&ref=ultralytics


In [ ]:
# set up environment
os.environ["DATASET_DIRECTORY"] = "/content/datasets"

In [ ]:
from roboflow import Roboflow
rf = Roboflow(api_key="eoGAyng4KmkxW7iaNkim")
project = rf.workspace("my-workspace-owlpm").project("calorie-estimation-tgx3k")
dataset = project.version(1).download("yolov5")

loading Roboflow workspace...
loading Roboflow project...


TypeError: ignored

In [ ]:
model = torch.hub.load('ultralytics/yolov5', 'custom', '/content/best_wts.pt')

## ANN to predict calories

In [ ]:
import numpy as np
import pandas as pd
import tensorflow as tf

In [ ]:
dataset = pd.read_csv('/content/Calorie-data.csv')
X = dataset.iloc[:, 1:-1].values
y = dataset.iloc[:, -1].values

In [ ]:
print(X)

[[    0.35096     0.27404      0.3125     0.26202           0]
 [    0.50481     0.36899     0.54207     0.43389           0]
 [    0.38942     0.27163     0.47115     0.36418           0]
 [    0.51803     0.38702     0.59495     0.47596           0]
 [    0.39543     0.30288     0.49159     0.37019           0]
 [    0.48678     0.36538     0.39663     0.34856           0]
 [    0.44712     0.32091     0.40505     0.32572           0]
 [    0.41466     0.30529      0.3125     0.27043           0]
 [     0.4399     0.32572     0.45913     0.34856           0]
 [    0.42428     0.29447      0.3762     0.29688           0]
 [    0.36899     0.29567     0.30769     0.25721           0]
 [    0.36899     0.28365     0.36659     0.30649           0]
 [    0.31731     0.23798     0.33534     0.26442           0]
 [    0.36298     0.30409     0.38702     0.36058           0]
 [    0.42668     0.35457     0.31851     0.26683           0]
 [    0.35096     0.26683     0.33173     0.26082      

In [ ]:
# from sklearn.compose import ColumnTransformer
# from sklearn.preprocessing import OneHotEncoder
# ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [4])], remainder = 'passthrough')
# X = np.array(ct.fit_transform(X).toarray())

In [ ]:
# print(X)

In [ ]:
ann = tf.keras.models.Sequential()

ann.add(tf.keras.layers.Dense(units=12, activation='relu', kernel_regularizer=tf.keras.regularizers.L1(1e-3), bias_regularizer=tf.keras.regularizers.L1(1e-3), activity_regularizer=tf.keras.regularizers.L1(1e-4)))
ann.add(tf.keras.layers.Dense(units=18, activation='relu', kernel_regularizer=tf.keras.regularizers.L1(1e-3), bias_regularizer=tf.keras.regularizers.L1(1e-3), activity_regularizer=tf.keras.regularizers.L1(1e-4)))
ann.add(tf.keras.layers.Dense(units=30, activation='relu', kernel_regularizer=tf.keras.regularizers.L1(1e-3), bias_regularizer=tf.keras.regularizers.L1(1e-3), activity_regularizer=tf.keras.regularizers.L1(1e-4)))
ann.add(tf.keras.layers.Dense(units=18, activation='relu', kernel_regularizer=tf.keras.regularizers.L1(1e-3), bias_regularizer=tf.keras.regularizers.L1(1e-3), activity_regularizer=tf.keras.regularizers.L1(1e-4)))
ann.add(tf.keras.layers.Dense(units=12, activation='relu', kernel_regularizer=tf.keras.regularizers.L1(1e-3), bias_regularizer=tf.keras.regularizers.L1(1e-3), activity_regularizer=tf.keras.regularizers.L1(1e-4)))
ann.add(tf.keras.layers.Dense(units=1))

In [ ]:
ann.compile(optimizer = 'adam', loss = 'mean_squared_error')

In [ ]:
ann.fit(X, y, batch_size = 8, epochs = 500)

In [ ]:
# *apple14, banana10, *bun4, *doughnut7

In [ ]:
imS = '/content/datasets/calorie-estimation-1/test/images/bun004S-8-_JPG.rf.af835e57aab7cac43149ffb1f3982071.jpg'  # or file, Path, URL, PIL, OpenCV, numpy, list

# Inference
results1 = model(imS)

# Results
results1.print()  # or .show(), .save(), .crop(), .pandas(), etc.

results1.xyxy[0]  # im predictions (tensor)
results1.pandas().xyxy[0]  # im predictions (pandas)

image 1/1: 416x416 1 bun, 1 coin
Speed: 13.8ms pre-process, 344.9ms inference, 1.3ms NMS per image at shape (1, 3, 640, 640)


xmin        ymin        xmax        ymax  confidence  class  name
0  231.978897  171.674088  398.161224  284.680481    0.947157      3   bun
1   38.785202  234.299210   76.477150  283.286926    0.940939      4  coin

In [ ]:
imT = '/content/datasets/calorie-estimation-1/test/images/bun004T-8-_JPG.rf.798f2dfafa38ff940641e08e9076f599.jpg'  # or file, Path, URL, PIL, OpenCV, numpy, list

# Inference
results2 = model(imT)

# Results
results2.print()  # or .show(), .save(), .crop(), .pandas(), etc.

results2.xyxy[0]  # im predictions (tensor)
results2.pandas().xyxy[0]  # im predictions (pandas)

image 1/1: 416x416 1 bun, 1 coin
Speed: 12.4ms pre-process, 341.8ms inference, 1.3ms NMS per image at shape (1, 3, 640, 640)


xmin        ymin        xmax        ymax  confidence  class  name
0  191.405533  118.837395  306.475739  346.697021    0.944095      3   bun
1   43.009560  146.179092   80.699890  195.213531    0.930570      4  coin

In [ ]:
confidence1 = results1.pandas().xyxy[0][results1.pandas().xyxy[0]['class']!=4]['confidence'].values.item()
hs = (results1.pandas().xyxy[0][results1.pandas().xyxy[0]['class']!=4]['ymax'].values.item() - results1.pandas().xyxy[0][results1.pandas().xyxy[0]['class']!=4]['ymin'].values.item())/416
ws = (results1.pandas().xyxy[0][results1.pandas().xyxy[0]['class']!=4]['xmax'].values.item() - results1.pandas().xyxy[0][results1.pandas().xyxy[0]['class']!=4]['xmin'].values.item())/416

In [ ]:
confidence2 = results2.pandas().xyxy[0][results2.pandas().xyxy[0]['class']!=4]['confidence'].values.item()
ht = (results2.pandas().xyxy[0][results2.pandas().xyxy[0]['class']!=4]['ymax'].values.item() - results2.pandas().xyxy[0][results2.pandas().xyxy[0]['class']!=4]['ymin'].values.item())/416
wt = (results2.pandas().xyxy[0][results2.pandas().xyxy[0]['class']!=4]['xmax'].values.item() - results2.pandas().xyxy[0][results2.pandas().xyxy[0]['class']!=4]['xmin'].values.item())/416

In [ ]:
class_name = results1.pandas().xyxy[0][results1.pandas().xyxy[0]['class']!=4]['class'].values.item()

In [ ]:
class_name

3

In [ ]:
X.shape

(146, 5)

In [ ]:
# a=[]
# for i in range(0,19):
    # a.append(0)
# a[class_name]=1

In [ ]:
# a = np.array(a)
# a

In [ ]:
# dims = np.array([ht,wt,hs,ws])

In [ ]:
# X_test = np.concatenate([a,dims])
X_test = [[ht,wt,hs,ws,class_name]]
Cal_predict=ann.predict(X_test)
Cal_predict

array([[     239.15]], dtype=float32)

---